---
- name: Converge
  hosts: all
  become: yes
  gather_facts: true
  ignore_errors: true
  
  vars:

    ignore_errors: true
    amazonlinux2cis_level1: true
    amazonlinux2cis_level2: false

  tasks:

    - name: "Include AmazonLinux-2-CIS"
      include_role:
        name: "AmazonLinux-2-CIS"
